### ISSUE TITLE
L2B: suspicious calc_*_grouping_stop_time definition

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/Aeolus-Server#48]
It is suspicious that the L2B `calc_*_grouping_stop_time` variables are defined in the same way as the `calc_*_grouping_start_time` ones.
https://github.com/ESA-VirES/Aeolus-Server/blob/20520382392d287075884539b3a8b7848fb6814a/aeolus/level_2b.py#L164-L182

This looks like a copy-paste error.

**Comment by pacesm** [comment]
Could anybody check this issue and, if the current code is right, close this ticket?

Is it really correct that the `*_start_time` and `*_stop_time` accessors both read the same **start** source parameters? Should not they be rather defined as ...

 ```
calc_mie_grouping_start_time = _make_grouping_time_accessor(
    'mie_grouping_start_obs',
    'mie_grouping_start_meas_per_obs',
)

calc_mie_grouping_stop_time = _make_grouping_time_accessor(
    'mie_grouping_end_obs',
    'mie_grouping_end_meas_per_obs',
)

calc_rayleigh_grouping_start_time = _make_grouping_time_accessor(
    'rayleigh_grouping_start_obs',
    'rayleigh_grouping_start_meas_per_obs',
)

calc_rayleigh_grouping_stop_time = _make_grouping_time_accessor(
    'rayleigh_grouping_end_obs',
    'rayleigh_grouping_end_meas_per_obs',
)
```

**Comment by santilland** [comment]
These parameters are no longer required and are being removed, thanks for the check!
