### ISSUE TITLE
Albedo: incorrect mapping to geographic to pixel coordinates

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/Aeolus-Server#50]
The ADAM albedo dataset provides a 3600x1800 raster dataset where each pixel covers area of 0.1x0.1 deg between -90 and +90 deg latitude and between -180 and +180 deg longitude.

The currently applied mapping to the pixel coordinates shifts the ADAM albedo grid by half pixel (rounding to nearest integer) and leads to out-of-bounds pixel coordinates for valid latitudes <= -89.95deg and longitudes >= 179.95deg.

https://github.com/ESA-VirES/Aeolus-Server/blob/20520382392d287075884539b3a8b7848fb6814a/aeolus/albedo.py#L82-L95

**Comment by constantinius** [comment]
As the Albedo pixels are considered to be areas I think it is sufficient to always round down.

Translated to code this means:

```python
 o_x = -180.0 
 o_y = 90.0 
  
 res_x = 360.0 / ds.RasterXSize 
 res_y = -180.0 / ds.RasterYSize 
  
 out_data = np.empty((len(lons),)) 
  
 for i, coord in enumerate(zip(lons, lats)): 
     lon, lat = coord 
  
     px = int((lon - o_x) / res_x)
     py = int((lat - o_y) / res_y)
     out_data[i] = band.ReadAsArray(px, py, 1, 1) 
```

**Comment by pacesm** [comment]
> As the Albedo pixels are considered to be areas I think it is sufficient to always round down.

This is true for -90deg < latitudes <= 90deg and -180deg <= longitude < +180deg. Though a valid latitude == -90deg or longitude == +180deg will still lead to out-of-bounds error.

Especially the +180deg longitude seems to be quite possible with a safeguards like `lons[lons > 180] -= 360`.

https://github.com/ESA-VirES/Aeolus-Server/blob/cd4d3b5d86f9dd0ea45fe22fe2e4b074dc545fcd/aeolus/level_1b.py#L214-L221
