### ISSUE TITLE
Implement data limit for download

### ISSUE THREAD

**Issue by santilland** [ESA-VirES/Aeolus-Server#56]
For users using the authentication token (currently only available in the oauth branch) the limit for data that can be accessed should be based on (result) file size instead of length of the time interval requested.
This is important as user might want to have highly filtered data for longer time periods.
I think the result size can't be really calculated, so the most sensible solution i can think of is to start collecting the data (i am not sure if this is done solely in memory or saved to disc), and once (or if) the data limit is reached it could either just send an error back, or send the data back plus additional information that the size limit has been reached.
Any other ideas of how to implement a size limit are of course also welcome.

**Comment by constantinius** [comment]
It is pretty much impossible to foresee how much space will be used for a final product, as with NetCDF, the data is likely internally compressed.

For NetCDF, each input product is iterated, so I suggest that after we have written data from one product, we check if the output file has exceeded the size limit and abort if it has.
