### ISSUE TITLE
Better inform user when requesting time interval where no products are found

### ISSUE THREAD

**Issue by santilland** [ESA-VirES/Aeolus-Server#57]
Currently when a user requests a time period where no products are available he just receives an empty response.
It would be good to somehow inform the user no actual products were found for the period he requested.

I think it is ok if an empty response is sent when for example through filters no results are in the response, but i think it is necessary to inform the user if the requested time did not include any product matches.

How best to notify the user can be discussed. We could consider maybe changing the response code to 204 "No content"?

**Comment by pacesm** [comment]
FYI, in Swarm we have the product traceability, i.e., additional to the data you also get the list of the source products. No source product means no data found.

**Comment by santilland** [comment]
good point, in principle we have the same in aeolus, i guess as a first step we try to better inform the user about this.

**Comment by santilland** [comment]
source traceability has been added, so for now i think we can close this issue
